#!/usr/bin/env bash
set -euox pipefail

function repo_root() {
  git rev-parse --show-toplevel
}

function project_version() {
  # VERSION derived from CHANGELOG and automated release library
  echo "$(<"$(repo_root)/VERSION")"
}

# Create a clean copy of the source code for build
cp -a /src /build
git config --global --add safe.directory /build
cd /build
git clean -fdx || :
# Copy the VERSION file generated by the CI to the build directory
cp /src/VERSION /build/VERSION

# Restore nuget packages
dotnet restore

# test
dotnet build
dotnet test --logger:"junit;LogFileName=/build/TestResults.xml"

# build
VERSION=$(project_version)
dotnet build api-dotnet.sln --configuration Release /p:AssemblyVersion="$VERSION"

# publish
if [ -z "${WRITE_ARTIFACTORY_URL:-}" ]; then
  echo "WRITE_ARTIFACTORY_URL is not set, skipping nuget push"
  exit 0
fi

docker/nuget.sh "$VERSION"
